version: "3.7"

services:
  tomcat-log4j2:
    build: ./tomcat-log4j2 docker
    ports:
      - "8088:8080"
    networks:
      - log4jnet
  pyhttp-server:
    build: ./pyhttp-server
    command: python3 -m http.server 10350
    volumes:
      - ./:/opt
    networks:
      - log4jnet
  openldap:
    image: bitnami/openldap:latest
    networks:
      - log4jnet
      
networks:
  log4jnet:
    driver: bridge
