version: "3.7"

services:
  tomcat-log4j2:
    build: ./tomcat-log4j2 docker
    ports:
      - "8088:8080"
    networks:
      - log4jnet
  pyhttp-server:
    build: ./pyhttp-server
    command: python3 -m http.server 10350
    volumes:
      - ./:/opt
    networks:
      - log4jnet
  openldap:
    image: bitnami/openldap:latest
    ports:
      - "1389:1389"
    networks:
      log4jnet:
        ipv4_address: 172.19.0.19
      
networks:
  log4jnet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
